"""
Signal handlers for the products app

Seperation of concerns, decouple approach
"""

from django.db.models.signals import pre_save
from django.dispatch import receiver
from django.utils.text import slugify

from .models import Category, Product, Tag


# Slug util

def generate_unique_slug(instance, slug_field: str = "slug", source_field: str = "name"):
    """
    Logic was generated by AI with directions on what I wanted:
    - lower case
    - removes special characters
    - replace spaaces with hyphens
    """
    if getattr(instance, slug_field):
        return
    base_slug = slugify(getattr(instance, source_field))
    slug = base_slug
    model_class = instance.__class__
    counter = 1
    while model_class.objects.filter(**{slug_field: slug}).exclude(pk=instance.pk).exists():
        slug = f"{base_slug}-{counter}"
        counter += 1
    setattr(instance, slug_field, slug)

@receiver(pre_save, sender=Category)
def category_pre_save(sender, instance, **kwargs):
    generate_unique_slug(instance)

@receiver(pre_save, sender=Tag)
def category_pre_save(sender, instance, **kwargs):
    generate_unique_slug(instance)

@receiver(pre_save, sender=Product)
def category_pre_save(sender, instance, **kwargs):
    generate_unique_slug(instance)